# Generated by Django 5.1.7 on 2025-03-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="player_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
