# Generated by Django 5.1.7 on 2025-04-08 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_remove_charactertraits_expires_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classtraits",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="classtraits",
            name="class_level_features",
        ),
        migrations.RemoveField(
            model_name="classtraits",
            name="traits",
        ),
        migrations.AlterField(
            model_name="attributes",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ability", "Ability"),
                    ("skill", "Skill"),
                    ("save", "Save"),
                    ("hp", "hp"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CharacterNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("backgrounds", "Backgrounds"), ("notes", "Notes")],
                        max_length=20,
                    ),
                ),
                ("context", models.CharField(max_length=255)),
                (
                    "characters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.characters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("long_rest", models.BooleanField(default=False)),
                ("short_rest", models.BooleanField(default=False)),
                ("value", models.IntegerField(default=0)),
                (
                    "characters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.characters",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharactersAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                (
                    "attributes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.attributes",
                    ),
                ),
                (
                    "characters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.characters",
                    ),
                ),
            ],
            options={
                "unique_together": {("characters", "attributes")},
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                ("rarity", models.IntegerField(default=1)),
                ("icon", models.CharField(max_length=255)),
                (
                    "rule_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.rulesystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.characters",
                    ),
                ),
                (
                    "items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.items"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spells",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("spell_level", models.IntegerField(default=0)),
                ("mp_cost", models.IntegerField(blank=True, null=True)),
                ("save_dc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rule_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.rulesystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "characters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.characters",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cards.spells"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ClassSkills",
        ),
        migrations.DeleteModel(
            name="ClassTraits",
        ),
    ]
